# Generated by Django 4.1.7 on 2023-04-16 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('conversion_value', models.FloatField(default=0, verbose_name='conversion value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_from', to='currency.currency', verbose_name='currency from')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_to', to='currency.currency', verbose_name='currency to')),
            ],
            options={
                'verbose_name': 'Currency conversion',
                'verbose_name_plural': 'Currency conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
