# Generated by Django 4.1.7 on 2023-03-11 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('conversion_data', models.TextField(default='{}', verbose_name='data conversion dictionary')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currency conversion',
                'verbose_name_plural': 'Currency conversions',
                'ordering': ['-created'],
            },
        ),
    ]
